### ISSUE TITLE
/opt/netmuxd: Exec format error

### ISSUE THREAD

**Issue by merentitis** [leapbtw/altserver-pi#1]
I am getting the following errors after starting the container:

`Creating altserver-pi_anisette_1 ... done
Creating altserver-pi_altserver_1 ... done
Attaching to altserver-pi_anisette_1, altserver-pi_altserver_1
altserver_1  | 
altserver_1  | ALTSERVER_ANISETTE_SERVER=http://127.0.0.1:6969/
altserver_1  | 
altserver_1  | Avahi daemon is running
altserver_1  | /opt/startup_script.sh: 12: /opt/netmuxd: Exec format error
altserver_1  | /opt/altserver: 1: Syntax error: "(" unexpected
altserver-pi_altserver_1 exited with code 2`

**Comment by leapbtw** [comment]
are you running it in x86? you should probably edit the scripts to `grep x86_64` or something like that

**Comment by merentitis** [comment]
Sorry for raising this up, I am using it inside a x64 vm, not a pi, so I believe I have to make some changes in order to work properly

**Comment by merentitis** [comment]
I edited Dockerfile and changed "grep aarch64" to "grep x86_64"
Thanks!
